import React from 'react';
import { AppState } from '../types';

interface ReportsTabProps {
  state: any;
  currentElder?: any;
}

export const ReportsTab: React.FC<ReportsTabProps> = ({ state }) => {
  const totalReminders = state.reminders.length;
  const completedReminders = state.reminders.filter(r => r.done).length;
  const missedReminders = totalReminders - completedReminders;
  const adherenceRate = totalReminders > 0 ? Math.round((completedReminders / totalReminders) * 100) : 0;

  const generateReport = () => {
    const report = `
CareAide Health Report
======================
Generated: ${new Date().toLocaleString()}

SUMMARY
-------
Total Reminders: ${totalReminders}
Completed: ${completedReminders}
Missed: ${missedReminders}
Adherence Rate: ${adherenceRate}%

VITALS
------
Blood Pressure Readings: ${state.vitals.bp.length}
Latest BP: ${state.vitals.bp.length > 0 ? state.vitals.bp[state.vitals.bp.length - 1].value : 'N/A'}

Blood Sugar Readings: ${state.vitals.sugar.length}
Latest Sugar: ${state.vitals.sugar.length > 0 ? state.vitals.sugar[state.vitals.sugar.length - 1].value : 'N/A'}

Water Intake Today: ${state.water}/8 glasses
Steps Today: ${state.steps}

FAMILY CONTACTS
--------------
${state.members.map(m => `${m.name} (${m.relation}): ${m.phone}${m.isEmergency ? ' [EMERGENCY]' : ''}`).join('\n')}

MEDICINES
---------
${state.medicines.map(m => `${m.name} - Qty: ${m.quantity}, Expires: ${m.expiry}`).join('\n')}

RECENT NOTES
-----------
${state.notes.slice(-5).map(n => `[${n.shift}] ${n.date}: ${n.note}`).join('\n')}

---
This report was generated by CareAide.
For medical advice, please consult a healthcare professional.
    `.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `careaide-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4 pb-20">
      {/* Summary Cards */}
      <div className="grid grid-cols-2 gap-3">
        <div className="bg-gradient-to-br from-blue-500 to-blue-600 rounded-xl p-4 text-white">
          <div className="text-3xl font-bold mb-1">{totalReminders}</div>
          <div className="text-sm opacity-90">Total Reminders</div>
        </div>
        <div className="bg-gradient-to-br from-green-500 to-green-600 rounded-xl p-4 text-white">
          <div className="text-3xl font-bold mb-1">{completedReminders}</div>
          <div className="text-sm opacity-90">Completed</div>
        </div>
        <div className="bg-gradient-to-br from-red-500 to-red-600 rounded-xl p-4 text-white">
          <div className="text-3xl font-bold mb-1">{missedReminders}</div>
          <div className="text-sm opacity-90">Missed</div>
        </div>
        <div className="bg-gradient-to-br from-purple-500 to-purple-600 rounded-xl p-4 text-white">
          <div className="text-3xl font-bold mb-1">{adherenceRate}%</div>
          <div className="text-sm opacity-90">Adherence</div>
        </div>
      </div>

      {/* Adherence Chart */}
      <div className="bg-white/10 backdrop-blur-md rounded-xl p-4">
        <h3 className="text-white font-semibold text-lg mb-3">Medication Adherence</h3>
        <div className="space-y-2">
          <div>
            <div className="flex justify-between text-white/80 text-sm mb-1">
              <span>Completed</span>
              <span>{adherenceRate}%</span>
            </div>
            <div className="w-full bg-white/20 rounded-full h-3">
              <div
                className="bg-green-500 h-3 rounded-full transition-all duration-500"
                style={{ width: `${adherenceRate}%` }}
              ></div>
            </div>
          </div>
        </div>
      </div>

      {/* Vitals Summary */}
      <div className="bg-white/10 backdrop-blur-md rounded-xl p-4">
        <h3 className="text-white font-semibold text-lg mb-3 flex items-center gap-2">
          <i className="fas fa-heartbeat"></i>
          Vitals Summary
        </h3>
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <i className="fas fa-heartbeat text-red-400"></i>
              <span className="text-white">Blood Pressure</span>
            </div>
            <span className="text-white font-semibold">
              {state.vitals.bp.length > 0
                ? state.vitals.bp[state.vitals.bp.length - 1].value
                : 'No data'}
            </span>
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <i className="fas fa-droplet text-blue-400"></i>
              <span className="text-white">Blood Sugar</span>
            </div>
            <span className="text-white font-semibold">
              {state.vitals.sugar.length > 0
                ? `${state.vitals.sugar[state.vitals.sugar.length - 1].value} mg/dL`
                : 'No data'}
            </span>
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <i className="fas fa-glass-water text-blue-300"></i>
              <span className="text-white">Water Intake</span>
            </div>
            <span className="text-white font-semibold">{state.water}/8 glasses</span>
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <i className="fas fa-shoe-prints text-green-400"></i>
              <span className="text-white">Steps</span>
            </div>
            <span className="text-white font-semibold">{state.steps}</span>
          </div>
        </div>
      </div>

      {/* ASHA Mode - Village Summary */}
      {state.mode === 'asha' && (
        <div className="bg-white/10 backdrop-blur-md rounded-xl p-4">
          <h3 className="text-white font-semibold text-lg mb-3 flex items-center gap-2">
            <i className="fas fa-building"></i>
            Village Health Summary
          </h3>
          <div className="space-y-2">
            <div className="flex justify-between text-white">
              <span>Total Elders Managed:</span>
              <span className="font-semibold">1</span>
            </div>
            <div className="flex justify-between text-white">
              <span>Average Adherence:</span>
              <span className="font-semibold">{adherenceRate}%</span>
            </div>
            <div className="flex justify-between text-white">
              <span>Total Family Members:</span>
              <span className="font-semibold">{state.members.length}</span>
            </div>
          </div>
        </div>
      )}

      {/* Recent Activity */}
      <div className="bg-white/10 backdrop-blur-md rounded-xl p-4">
        <h3 className="text-white font-semibold text-lg mb-3 flex items-center gap-2">
          <i className="fas fa-clock"></i>
          Recent Activity
        </h3>
        <div className="space-y-2">
          {state.reminders.slice(-5).reverse().map((reminder) => (
            <div
              key={reminder.id}
              className="bg-white/20 rounded-lg p-2 flex items-center justify-between"
            >
              <div className="flex items-center gap-2">
                <i className={`fas fa-${reminder.done ? 'check-circle text-green-400' : 'clock text-yellow-400'}`}></i>
                <span className="text-white">{reminder.title}</span>
              </div>
              <span className="text-white/60 text-sm">{reminder.time}</span>
            </div>
          ))}
          {state.reminders.length === 0 && (
            <p className="text-white/60 text-center py-4">No recent activity</p>
          )}
        </div>
      </div>

      {/* Download Report */}
      <button
        onClick={generateReport}
        className="w-full bg-[#13c5dd] hover:bg-[#10a8bd] text-white font-semibold py-4 px-6 rounded-xl shadow-md flex items-center justify-center gap-2"
      >
        <i className="fas fa-download"></i>
        Download Full Report (TXT)
      </button>

      {/* UBA Impact Note */}
      {(state.mode === 'asha' || state.appMode === 'advanced') && (
        <div className="bg-gradient-to-br from-orange-500/20 to-red-500/20 backdrop-blur-md rounded-xl p-4 border border-orange-500/30">
          <h4 className="text-orange-200 font-semibold mb-2 flex items-center gap-2">
            <i className="fas fa-flag-india"></i>
            UBA Impact Tracking
          </h4>
          <p className="text-orange-100/80 text-sm">
            This data can be used for Unnat Bharat Abhiyan (UBA) reporting and impact assessment.
            Track improvements in medication adherence and health outcomes over time.
          </p>
        </div>
      )}
    </div>
  );
};
